name: deborduurshop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
#  dio: ^5.3.2
  retrofit: ^4.0.1
  lottie: any
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  device_info_plus: ^9.0.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  fluttertoast: ^8.2.1
  another_flushbar: ^1.12.29
  syncfusion_flutter_pdfviewer: ^23.1.36
  pdf: ^3.10.4
  flutter_udid: ^2.0.1
  provider: ^6.1.1
  sqflite: ^2.3.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  open_file: ^3.3.2
  hive_flutter: ^1.1.0
  syncfusion_flutter_pdf: ^23.2.7
  custom_pdf_converter: ^3.10.4
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_page_img.png
